services:
  - type: web
    name: secureiq-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 30
    envVars:
      - key: VIRUSTOTAL_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
