import React, { useState } from 'react';

export default function AboutPage() {
  const [faqs, setFaqs] = useState({ faq1: true, faq2: false, faq3: false });

  const toggleFaq = (key) => {
    setFaqs((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <div className="flex flex-col gap-8">
      <div className="bg-surface border border-brandBorder rounded-md p-8 shadow-sm">
        <div className="mb-2">
          <span className="text-xs font-mono font-medium text-brandText-muted bg-subtle px-2 py-1 border border-brandBorder-subtle rounded-sm mb-2 inline-block">
            HELP CENTER & DOCUMENTATION
          </span>
          <h1 className="font-heading text-2xl font-semibold text-brandText-main">About SecureIQ & Knowledge Base</h1>
          <p className="text-sm text-brandText-muted mt-1">Learn how SecureIQ uses ML inference and lexical heuristics to stop credential harvesting, phishing, and email spoofing.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-surface border border-brandBorder rounded-md p-6 shadow-sm">
          <div className="font-semibold text-brandText-main mb-2 text-sm">Our Mission</div>
          <p className="text-xs text-brandText-muted leading-relaxed">Eliminate digital deception and credential theft by delivering real-time, explainable security intelligence to every organization and end user.</p>
        </div>
        <div className="bg-surface border border-brandBorder rounded-md p-6 shadow-sm">
          <div className="font-semibold text-brandText-main mb-2 text-sm">Core Technology</div>
          <p className="text-xs text-brandText-muted leading-relaxed">Combines Gradient Boosting machine learning models with deterministic Shannon entropy evaluation and real-time DNS/TLS protocol inspection.</p>
        </div>
        <div className="bg-surface border border-brandBorder rounded-md p-6 shadow-sm">
          <div className="font-semibold text-brandText-main mb-2 text-sm">Privacy First</div>
          <p className="text-xs text-brandText-muted leading-relaxed">We analyze string structures and headers statelessly. No personal user credentials or private email bodies are stored without consent.</p>
        </div>
      </div>

      <div className="signals-container">
        <div className="signals-header">
          <h2 className="signals-title">Frequently Asked Questions</h2>
        </div>
        <div className="p-6 flex flex-col gap-4">
          <div className="border-b border-brandBorder-subtle pb-3">
            <h3 className="text-base font-semibold cursor-pointer text-navy" onClick={() => toggleFaq('faq1')}>
              ❓ How does SecureIQ calculate the Risk Score?
            </h3>
            {faqs.faq1 && (
              <p className="text-sm text-brandText-secondary mt-1.5 leading-relaxed">
                The risk score (0-100) is generated by aggregating weights from lexical tokenizers (e.g., domain age, TLD risk, hyphen density), TLS certificate validation, IP host detection, and gradient boosted ML model predictions trained on millions of benign and malicious URLs.
              </p>
            )}
          </div>

          <div className="border-b border-brandBorder-subtle pb-3">
            <h3 className="text-base font-semibold cursor-pointer text-navy" onClick={() => toggleFaq('faq2')}>
              ❓ What is the difference between URL Scanner and Email Scanner?
            </h3>
            {faqs.faq2 && (
              <p className="text-sm text-brandText-secondary mt-1.5 leading-relaxed">
                The URL Scanner focuses strictly on target link metrics (DNS, protocol, entropy). The Email Scanner inspects RFC-822 header alignment (SPF, DKIM, Reply-To mismatches), social engineering urgency triggers, and embedded links inside emails.
              </p>
            )}
          </div>

          <div>
            <h3 className="text-base font-semibold cursor-pointer text-navy" onClick={() => toggleFaq('faq3')}>
              ❓ How do I integrate the API into my existing SIEM/SOAR?
            </h3>
            {faqs.faq3 && (
              <p className="text-sm text-brandText-secondary mt-1.5 leading-relaxed">
                Issue an API key from the Settings page and send JSON payloads to <code className="bg-subtle px-1">POST /analyze</code> with headers <code className="bg-subtle px-1">Authorization: Bearer YOUR_API_KEY</code>. Returns full JSON telemetry including signals breakdown.
              </p>
            )}
          </div>
        </div>
      </div>

      <div className="signals-container">
        <div className="signals-header">
          <h2 className="signals-title">Contact Support & Feedback</h2>
        </div>
        <div className="p-6">
          <form onSubmit={(e) => { e.preventDefault(); alert('Thank you for your feedback! Our security team will review it.'); }}>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-brandText-secondary">Your Name</label>
                <input type="text" className="h-10 px-3 font-body text-sm text-brandText-main bg-surface border border-brandBorder-strong rounded-md" placeholder="Jane Doe" required />
              </div>
              <div className="flex flex-col gap-1.5">
                <label className="text-xs font-semibold text-brandText-secondary">Email Address</label>
                <input type="email" className="h-10 px-3 font-body text-sm text-brandText-main bg-surface border border-brandBorder-strong rounded-md" placeholder="jane@company.com" required />
              </div>
            </div>
            <div className="flex flex-col gap-1.5 mb-4">
              <label className="text-xs font-semibold text-brandText-secondary">Feedback or False Positive Report</label>
              <textarea className="h-24 p-3 font-body text-sm text-brandText-main bg-surface border border-brandBorder-strong rounded-md" placeholder="Describe the question or domain false positive report..." required></textarea>
            </div>
            <button type="submit" className="btn-primary">Submit Inquiry</button>
          </form>
        </div>
      </div>
    </div>
  );
}
